auto-update KEGG db

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -19,9 +19,36 @@ cache:
   directories:
   - $HOME/.m2
 
+env:
+  global:
+  - TARGET_REPO="github.com/MGX-metagenomics/MGX-gui.git"
+
 before_install:
   - sudo apt-get update -qq
   - sudo apt-get install -qq protobuf-compiler
 
 script:
   - mvn clean install
+
+after_success: |
+  if [ -n "$GITHUB_API_KEY" ]; then
+    cd "$TRAVIS_BUILD_DIR"
+    # fetch KEGG data
+    cd KEGG-Pathways/target && java -jar KEGG-Pathways-1.0.jar
+    git clone git://${TARGET_REPO}
+    SRC=/tmp/kegg/kegg.mv.db
+    TRG="MGX-gui/MGX-KeggViewer/src/main/resources/de/cebitec/mgx/gui/keggviewer/kegg.mv.db"
+    if [ ! $(cmp -s ${SRC} ${TRG} ) ]; then
+      MESSAGE="Automatic KEGG database update via Travis CI build #${TRAVIS_BUILD_NUMBER}."
+      git config --global user.name "Travis CI"
+      git config --global user.email "travis@travis-ci.org"
+      cp ${SRC} ${TRG}
+      cd MGX-gui
+      git commit -m ${MESSAGE} MGX-KeggViewer/src/main/resources/de/cebitec/mgx/gui/keggviewer/kegg.mv.db
+      git push -q "https://${GITHUB_API_KEY}@${TARGET_REPO}" master || echo "Git push failed."
+    else
+      echo "KEGG database unchanged."
+    fi
+  else
+    echo "No GitHub API key found."
+  fi
