fix automated KEGG db update

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -36,7 +36,7 @@ after_success: |
   if [ -n "$GITHUB_API_KEY" ]; then
     cd "$TRAVIS_BUILD_DIR"
     # fetch KEGG data
-    cd KEGG-Pathways/target && java -jar KEGG-Pathways-1.0.jar
+    cd KEGG-Pathways/target && java -jar KEGG-Pathways-2.0.jar
     git clone -b MGX_gui_2_0 git://${TARGET_REPO}
     SRC=/tmp/kegg/kegg.mv.db
     TRG="MGX-gui/MGX-KeggViewer/src/main/resources/de/cebitec/mgx/gui/keggviewer/kegg.mv.db"
@@ -47,7 +47,7 @@ after_success: |
       cp ${SRC} ${TRG}
       cd MGX-gui
       git commit -m "${MESSAGE}" MGX-KeggViewer/src/main/resources/de/cebitec/mgx/gui/keggviewer/kegg.mv.db
-      git push -q "https://${GITHUB_API_KEY}@${TARGET_REPO}" master || echo "Git push failed."
+      git push -q "https://${GITHUB_API_KEY}@${TARGET_REPO}" MGX_gui_2_0 || echo "Git push failed."
     else
       echo "KEGG database unchanged."
     fi
